[build]
  command = "vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_PRIVATE_TARGET = ""
  NEXT_TELEMETRY_DISABLED = "1"

# 完全移除Next.js插件配置，避免Netlify误判
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
#   enabled = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
  Content-Type = "application/manifest+json"